### ISSUE TITLE
Doxygen-Generierung einrichten

### ISSUE THREAD

**Issue by tcm-marcel** [minijavacc/minijavacc#15]
am Besten mit Skript, das automatisch in /docs generiert

**Comment by Rolleander** [comment]
soll zu allem doku generiert werden, oder nur für die Ast-klassen? Weil dann müsstet ihr noch angeben in welchem ordner die dann liegen werden.

**Comment by tcm-marcel** [comment]
vorerst nur für die AST-Klassen, die Deklarationen liegen bisher in /parser/node.hpp. Die Struktur ändert sich aber nochmal (siehe #10) und erst dann kommen die Dokumentationskommentare.

**Comment by Rolleander** [comment]
ich hab jetzt mal die meisten einstellungen auf standard gelassen und momentan wird zu allem doku generiert, was im parser/ ordner drin ist (da landen ja dann die einzelnen ast klassen denk ich mal). das script generate_docu ruft doxygen entsprechend auf, die doku landet in einem extra ordner "doc". dort kann man sich dann das ergebnis als html oder latex anschauen (am einfachsten die index.html öffnen und fertig). wenn wir noch ein paar einstellungen ändern müssen kann man das jederzeit in der Doxyfile machen. Bei mir läufts wunderbar.
