### ISSUE TITLE
String-Tabelle bauen

### ISSUE THREAD

**Issue by minijavacc** [minijavacc/minijavacc#6]

**Comment by tcm-marcel** [comment]
implementiert, aber die Initialisierung in der Compiler-Klasse mit den Keywords fehlt noch (daher mal offen gelassen)

**Comment by minijavacc** [comment]
TODO: Aktuell steht der String im Container, weil wir den für --lextest brauchen. Speichersparender wäre es, eine zweite Hashmap zu führen, die von IdentifierTokenId nach entsprechendem String mappt.
