### ISSUE TITLE
Testscripts in ordentlich

### ISSUE THREAD

**Issue by minijavacc** [minijavacc/minijavacc#8]
Die Scripts sind bisher ohne großes Sachverständnis runtergetippt. Jemand mit Ahnung könnte das robuster machen.

build_and_test
src/lexer/tests/test.sh
src/lexer/tests/single_test_cases.sh

Feel free to assign yourselves

**Comment by tcm-marcel** [comment]
Hier könnte man evtl. das Test-Repo mit einbauen
